#n = int(input('Digite algo: '))
#n = float(input('Digite algo: '))
#n = bool(input('Digite algo: '))
#n = str(input('Digite algo: '))
n = input('Digite algo: ')
#print(n.isnumeric())
print(n.isalpha())
